name: 部署博客
# 关键权限配置，必须放在最顶部
permissions:
  contents: write
  pages: write
  id-token: write

# 触发条件：main分支推送代码时运行
on:
  push:
    branches: [ main ]
  workflow_dispatch: # 支持手动点按钮运行

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 拉取仓库代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 配置Node环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
        

      # 3. 安装依赖
      - name: Install dependencies
        run: npm install

      # 4. 打包生成静态页面
      - name: Build site
        run: npm run build

      # 5. 上传打包后的静态文件（替换path为你的打包输出文件夹，dist/public/.vitepress/dist）
      - name: Upload static artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      # 6. 官方部署Pages，不会出现gh-pages推送403报错
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
